name: Daily Paper

on:
  workflow_dispatch:
  schedule:
    - cron: "1 18 * * *"

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install requests

      - name: Send paper
        run: python papers.py
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT: ${{ secrets.TG_CHAT }}
